const RANDOM_NAMES = [
"Pavin fraudeur de la RATP", 
"Pavin cheminot", 
"Pavin agriculteur", 
"Pavin xénophobe", 
"Pavin macroniste", 
"Pavin mange gadou", 
"Pavin warwick", 
"Pavin énervé", 
"Pavin énervé", 
"Pavin énervé", 
"Pavin énervé", 
"Pavin bagareur", 
"Pavin bagareur", 
"Pavin bagareur", 
"Pavin bagareur", 
"Pavin combattant", 
"Pavin combattant", 
"Pavin combattant", 
"Pavin combattant", 
"Pavin magicien", 
"Pavin magicien", 
"Pavin magicien", 
"Pavin magicien", 
"Pavin random", 
"Pavin random", 
"Pavin random", 
"Pavin random", 
"Pavin random", 

];